#ifndef ZGBMAIN_H
#define ZGBMAIN_H

#define STATES \
_STATE(STATE_TITLE)\
_STATE(STATE_GAME)\
_STATE(STATE_GAMEOVER)\
STATE_DEF_END

#define SPRITES \
_SPRITE_DMG(SPRITE_PLAYER, player, 3, FRAME_16x16, 4)\
_SPRITE_DMG(SPRITE_PLAYER2, player, 3, FRAME_16x16, 4)\
_SPRITE_DMG(SPRITE_PLAYER3, player, 3, FRAME_16x16, 4)\
_SPRITE_DMG(SPRITE_WORM,  worm,  3, FRAME_16x16, 2)\
_SPRITE_DMG(SPRITE_ROCK,  rock,  3, FRAME_16x16, 2)\
_SPRITE_DMG(SPRITE_GOB, gameoverbird, 3, FRAME_16x16, 2)\
_SPRITE_DMG(SPRITE_GOM, gameovermad, 3, FRAME_16x16, 2)\
SPRITE_DEF_END

#include "ZGBMain_Init.h"

#endif